/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PrdIndexRouteImport } from './routes/prd/index'
import { Route as PrdPrdIdRouteImport } from './routes/prd/$prdId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdIndexRoute = PrdIndexRouteImport.update({
  id: '/prd/',
  path: '/prd/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrdPrdIdRoute = PrdPrdIdRouteImport.update({
  id: '/prd/$prdId',
  path: '/prd/$prdId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prd/$prdId': typeof PrdPrdIdRoute
  '/prd': typeof PrdIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prd/$prdId': typeof PrdPrdIdRoute
  '/prd': typeof PrdIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prd/$prdId': typeof PrdPrdIdRoute
  '/prd/': typeof PrdIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prd/$prdId' | '/prd' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prd/$prdId' | '/prd' | '/settings'
  id: '__root__' | '/' | '/prd/$prdId' | '/prd/' | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrdPrdIdRoute: typeof PrdPrdIdRoute
  PrdIndexRoute: typeof PrdIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd/': {
      id: '/prd/'
      path: '/prd'
      fullPath: '/prd'
      preLoaderRoute: typeof PrdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prd/$prdId': {
      id: '/prd/$prdId'
      path: '/prd/$prdId'
      fullPath: '/prd/$prdId'
      preLoaderRoute: typeof PrdPrdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrdPrdIdRoute: PrdPrdIdRoute,
  PrdIndexRoute: PrdIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
